version: '3'

services:
  xmrig:
    build:
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "3003:3003"
    volumes:
      - "./miner_data:/tmp"
      - "/lib/modules:/lib/modules"
    environment:
      - log-file=/tmp/xmrig.log
      - XMRIG_VER=6.16.2
